language: R
cache:
  packages: true
  
addons:
  apt:
    packages:
      - libxml2-dev

r_packages:
  - covr
  - RSelenium
  - magrittr
  - stringr
  - stringi

after_success:
  - Rscript -e 'library(covr); codecov()'
