sudo: required
language: R
r_github_packages:
  - ropensci/RSelenium
r:
  - release
  - devel
cache:
  packages: true
warnings_are_errors: false
addons:
  apt:
    packages:
      - libxml2-dev
r_packages:
  - covr
  - lubridate
  - dplyr
  - magrittr
  - stringr
  - stringi
after_success:
  - Rscript -e 'library(covr); codecov()'
